### ISSUE TITLE
Nowdoc syntax error in NetBeans.

### ISSUE THREAD

**Issue by sfadschm** [NexusPHP/cs-config#2]
Hi Paul,
was just wondering why NetBeans keeps throwing syntax errors for cs-config. Do the single quote here have any meaning:
https://github.com/NexusPHP/cs-config/blob/d484c245fef2f79364448b8b377ccc33a6acfded/src/Fixer/Comment/NoCodeSeparatorCommentFixer.php#L37
compared to 
https://github.com/NexusPHP/cs-config/blob/d484c245fef2f79364448b8b377ccc33a6acfded/src/Fixer/Comment/NoCodeSeparatorCommentFixer.php#L46
According to the Heredoc documentation I would think that the opening and closing identifiers should be strictly equal.

**Comment by paulbalandan** [comment]
This is nowdoc syntax. This behaves exactly like heredoc except that there is no string substitution taking place. Can you check the PHP version used by NetBeans in parsing the code? If it is below PHP 7.3 I think it errors on the indentation of the identifiers.

**Comment by sfadschm** [comment]
Correct, my bad.
However, NetBeans ist set to 8.0. I tried playing with the indentation, but nothing resolved this.
I conclude that this is likely a NetBeans issue as the code is working and just excluded the whole vendor folder from code checks.

Thanks for the quick answer!
